// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.6.0 (commit 3c16edb3503eab8aad562e011d7fb452e051267d).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { AddConversationMessage } from "./add_conversation_message_reducer.ts";
export { AddConversationMessage };
import { ClientConnected } from "./client_connected_reducer.ts";
export { ClientConnected };
import { ClientDisconnected } from "./client_disconnected_reducer.ts";
export { ClientDisconnected };
import { GetRecentMetrics } from "./get_recent_metrics_reducer.ts";
export { GetRecentMetrics };
import { LogTrainingEvent } from "./log_training_event_reducer.ts";
export { LogTrainingEvent };
import { MasterPattern } from "./master_pattern_reducer.ts";
export { MasterPattern };
import { SaveNetworkSnapshot } from "./save_network_snapshot_reducer.ts";
export { SaveNetworkSnapshot };
import { SetTrainingStatus } from "./set_training_status_reducer.ts";
export { SetTrainingStatus };
import { StartPattern } from "./start_pattern_reducer.ts";
export { StartPattern };
import { UpdateSageState } from "./update_sage_state_reducer.ts";
export { UpdateSageState };

// Import and reexport all table handle types
import { ConversationsTableHandle } from "./conversations_table.ts";
export { ConversationsTableHandle };
import { NetworkSnapshotsTableHandle } from "./network_snapshots_table.ts";
export { NetworkSnapshotsTableHandle };
import { PatternProgressTableHandle } from "./pattern_progress_table.ts";
export { PatternProgressTableHandle };
import { SageStateTableHandle } from "./sage_state_table.ts";
export { SageStateTableHandle };
import { TrainingEventsTableHandle } from "./training_events_table.ts";
export { TrainingEventsTableHandle };
import { TrainingMetricsTableHandle } from "./training_metrics_table.ts";
export { TrainingMetricsTableHandle };

// Import and reexport all types
import { Conversation } from "./conversation_type.ts";
export { Conversation };
import { NetworkSnapshot } from "./network_snapshot_type.ts";
export { NetworkSnapshot };
import { PatternProgress } from "./pattern_progress_type.ts";
export { PatternProgress };
import { SageState } from "./sage_state_type.ts";
export { SageState };
import { TrainingEvent } from "./training_event_type.ts";
export { TrainingEvent };
import { TrainingMetrics } from "./training_metrics_type.ts";
export { TrainingMetrics };

const REMOTE_MODULE = {
  tables: {
    conversations: {
      tableName: "conversations" as const,
      rowType: Conversation.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Conversation.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    network_snapshots: {
      tableName: "network_snapshots" as const,
      rowType: NetworkSnapshot.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (NetworkSnapshot.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    pattern_progress: {
      tableName: "pattern_progress" as const,
      rowType: PatternProgress.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (PatternProgress.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    sage_state: {
      tableName: "sage_state" as const,
      rowType: SageState.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (SageState.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    training_events: {
      tableName: "training_events" as const,
      rowType: TrainingEvent.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (TrainingEvent.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    training_metrics: {
      tableName: "training_metrics" as const,
      rowType: TrainingMetrics.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (TrainingMetrics.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    add_conversation_message: {
      reducerName: "add_conversation_message",
      argsType: AddConversationMessage.getTypeScriptAlgebraicType(),
    },
    client_connected: {
      reducerName: "client_connected",
      argsType: ClientConnected.getTypeScriptAlgebraicType(),
    },
    client_disconnected: {
      reducerName: "client_disconnected",
      argsType: ClientDisconnected.getTypeScriptAlgebraicType(),
    },
    get_recent_metrics: {
      reducerName: "get_recent_metrics",
      argsType: GetRecentMetrics.getTypeScriptAlgebraicType(),
    },
    log_training_event: {
      reducerName: "log_training_event",
      argsType: LogTrainingEvent.getTypeScriptAlgebraicType(),
    },
    master_pattern: {
      reducerName: "master_pattern",
      argsType: MasterPattern.getTypeScriptAlgebraicType(),
    },
    save_network_snapshot: {
      reducerName: "save_network_snapshot",
      argsType: SaveNetworkSnapshot.getTypeScriptAlgebraicType(),
    },
    set_training_status: {
      reducerName: "set_training_status",
      argsType: SetTrainingStatus.getTypeScriptAlgebraicType(),
    },
    start_pattern: {
      reducerName: "start_pattern",
      argsType: StartPattern.getTypeScriptAlgebraicType(),
    },
    update_sage_state: {
      reducerName: "update_sage_state",
      argsType: UpdateSageState.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.6.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "AddConversationMessage", args: AddConversationMessage }
| { name: "ClientConnected", args: ClientConnected }
| { name: "ClientDisconnected", args: ClientDisconnected }
| { name: "GetRecentMetrics", args: GetRecentMetrics }
| { name: "LogTrainingEvent", args: LogTrainingEvent }
| { name: "MasterPattern", args: MasterPattern }
| { name: "SaveNetworkSnapshot", args: SaveNetworkSnapshot }
| { name: "SetTrainingStatus", args: SetTrainingStatus }
| { name: "StartPattern", args: StartPattern }
| { name: "UpdateSageState", args: UpdateSageState }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  addConversationMessage(sender: string, message: string, generationContext: bigint) {
    const __args = { sender, message, generationContext };
    let __writer = new __BinaryWriter(1024);
    AddConversationMessage.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_conversation_message", __argsBuffer, this.setCallReducerFlags.addConversationMessageFlags);
  }

  onAddConversationMessage(callback: (ctx: ReducerEventContext, sender: string, message: string, generationContext: bigint) => void) {
    this.connection.onReducer("add_conversation_message", callback);
  }

  removeOnAddConversationMessage(callback: (ctx: ReducerEventContext, sender: string, message: string, generationContext: bigint) => void) {
    this.connection.offReducer("add_conversation_message", callback);
  }

  onClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("client_connected", callback);
  }

  removeOnClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("client_connected", callback);
  }

  onClientDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("client_disconnected", callback);
  }

  removeOnClientDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("client_disconnected", callback);
  }

  getRecentMetrics(limit: number) {
    const __args = { limit };
    let __writer = new __BinaryWriter(1024);
    GetRecentMetrics.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("get_recent_metrics", __argsBuffer, this.setCallReducerFlags.getRecentMetricsFlags);
  }

  onGetRecentMetrics(callback: (ctx: ReducerEventContext, limit: number) => void) {
    this.connection.onReducer("get_recent_metrics", callback);
  }

  removeOnGetRecentMetrics(callback: (ctx: ReducerEventContext, limit: number) => void) {
    this.connection.offReducer("get_recent_metrics", callback);
  }

  logTrainingEvent(generation: bigint, eventType: string, description: string) {
    const __args = { generation, eventType, description };
    let __writer = new __BinaryWriter(1024);
    LogTrainingEvent.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("log_training_event", __argsBuffer, this.setCallReducerFlags.logTrainingEventFlags);
  }

  onLogTrainingEvent(callback: (ctx: ReducerEventContext, generation: bigint, eventType: string, description: string) => void) {
    this.connection.onReducer("log_training_event", callback);
  }

  removeOnLogTrainingEvent(callback: (ctx: ReducerEventContext, generation: bigint, eventType: string, description: string) => void) {
    this.connection.offReducer("log_training_event", callback);
  }

  masterPattern(pattern: string, generation: bigint, finalLoss: number) {
    const __args = { pattern, generation, finalLoss };
    let __writer = new __BinaryWriter(1024);
    MasterPattern.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("master_pattern", __argsBuffer, this.setCallReducerFlags.masterPatternFlags);
  }

  onMasterPattern(callback: (ctx: ReducerEventContext, pattern: string, generation: bigint, finalLoss: number) => void) {
    this.connection.onReducer("master_pattern", callback);
  }

  removeOnMasterPattern(callback: (ctx: ReducerEventContext, pattern: string, generation: bigint, finalLoss: number) => void) {
    this.connection.offReducer("master_pattern", callback);
  }

  saveNetworkSnapshot(generation: bigint, pattern: string, loss: number, weightsJson: string) {
    const __args = { generation, pattern, loss, weightsJson };
    let __writer = new __BinaryWriter(1024);
    SaveNetworkSnapshot.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("save_network_snapshot", __argsBuffer, this.setCallReducerFlags.saveNetworkSnapshotFlags);
  }

  onSaveNetworkSnapshot(callback: (ctx: ReducerEventContext, generation: bigint, pattern: string, loss: number, weightsJson: string) => void) {
    this.connection.onReducer("save_network_snapshot", callback);
  }

  removeOnSaveNetworkSnapshot(callback: (ctx: ReducerEventContext, generation: bigint, pattern: string, loss: number, weightsJson: string) => void) {
    this.connection.offReducer("save_network_snapshot", callback);
  }

  setTrainingStatus(isTraining: boolean) {
    const __args = { isTraining };
    let __writer = new __BinaryWriter(1024);
    SetTrainingStatus.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_training_status", __argsBuffer, this.setCallReducerFlags.setTrainingStatusFlags);
  }

  onSetTrainingStatus(callback: (ctx: ReducerEventContext, isTraining: boolean) => void) {
    this.connection.onReducer("set_training_status", callback);
  }

  removeOnSetTrainingStatus(callback: (ctx: ReducerEventContext, isTraining: boolean) => void) {
    this.connection.offReducer("set_training_status", callback);
  }

  startPattern(pattern: string, generation: bigint) {
    const __args = { pattern, generation };
    let __writer = new __BinaryWriter(1024);
    StartPattern.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("start_pattern", __argsBuffer, this.setCallReducerFlags.startPatternFlags);
  }

  onStartPattern(callback: (ctx: ReducerEventContext, pattern: string, generation: bigint) => void) {
    this.connection.onReducer("start_pattern", callback);
  }

  removeOnStartPattern(callback: (ctx: ReducerEventContext, pattern: string, generation: bigint) => void) {
    this.connection.offReducer("start_pattern", callback);
  }

  updateSageState(generation: bigint, loss: number, pattern: string, complexity: number, diversity: number) {
    const __args = { generation, loss, pattern, complexity, diversity };
    let __writer = new __BinaryWriter(1024);
    UpdateSageState.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_sage_state", __argsBuffer, this.setCallReducerFlags.updateSageStateFlags);
  }

  onUpdateSageState(callback: (ctx: ReducerEventContext, generation: bigint, loss: number, pattern: string, complexity: number, diversity: number) => void) {
    this.connection.onReducer("update_sage_state", callback);
  }

  removeOnUpdateSageState(callback: (ctx: ReducerEventContext, generation: bigint, loss: number, pattern: string, complexity: number, diversity: number) => void) {
    this.connection.offReducer("update_sage_state", callback);
  }

}

export class SetReducerFlags {
  addConversationMessageFlags: __CallReducerFlags = 'FullUpdate';
  addConversationMessage(flags: __CallReducerFlags) {
    this.addConversationMessageFlags = flags;
  }

  getRecentMetricsFlags: __CallReducerFlags = 'FullUpdate';
  getRecentMetrics(flags: __CallReducerFlags) {
    this.getRecentMetricsFlags = flags;
  }

  logTrainingEventFlags: __CallReducerFlags = 'FullUpdate';
  logTrainingEvent(flags: __CallReducerFlags) {
    this.logTrainingEventFlags = flags;
  }

  masterPatternFlags: __CallReducerFlags = 'FullUpdate';
  masterPattern(flags: __CallReducerFlags) {
    this.masterPatternFlags = flags;
  }

  saveNetworkSnapshotFlags: __CallReducerFlags = 'FullUpdate';
  saveNetworkSnapshot(flags: __CallReducerFlags) {
    this.saveNetworkSnapshotFlags = flags;
  }

  setTrainingStatusFlags: __CallReducerFlags = 'FullUpdate';
  setTrainingStatus(flags: __CallReducerFlags) {
    this.setTrainingStatusFlags = flags;
  }

  startPatternFlags: __CallReducerFlags = 'FullUpdate';
  startPattern(flags: __CallReducerFlags) {
    this.startPatternFlags = flags;
  }

  updateSageStateFlags: __CallReducerFlags = 'FullUpdate';
  updateSageState(flags: __CallReducerFlags) {
    this.updateSageStateFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get conversations(): ConversationsTableHandle<'conversations'> {
    // clientCache is a private property
    return new ConversationsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Conversation>(REMOTE_MODULE.tables.conversations));
  }

  get networkSnapshots(): NetworkSnapshotsTableHandle<'network_snapshots'> {
    // clientCache is a private property
    return new NetworkSnapshotsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<NetworkSnapshot>(REMOTE_MODULE.tables.network_snapshots));
  }

  get patternProgress(): PatternProgressTableHandle<'pattern_progress'> {
    // clientCache is a private property
    return new PatternProgressTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PatternProgress>(REMOTE_MODULE.tables.pattern_progress));
  }

  get sageState(): SageStateTableHandle<'sage_state'> {
    // clientCache is a private property
    return new SageStateTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<SageState>(REMOTE_MODULE.tables.sage_state));
  }

  get trainingEvents(): TrainingEventsTableHandle<'training_events'> {
    // clientCache is a private property
    return new TrainingEventsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<TrainingEvent>(REMOTE_MODULE.tables.training_events));
  }

  get trainingMetrics(): TrainingMetricsTableHandle<'training_metrics'> {
    // clientCache is a private property
    return new TrainingMetricsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<TrainingMetrics>(REMOTE_MODULE.tables.training_metrics));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
