// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type PatternProgress = {
  id: bigint,
  pattern: string,
  startGeneration: bigint,
  masteredGeneration: bigint | undefined,
  bestLoss: number,
  isMastered: boolean,
  startedAt: __Timestamp,
  masteredAt: __Timestamp | undefined,
};
let _cached_PatternProgress_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const PatternProgress = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_PatternProgress_type_value) return _cached_PatternProgress_type_value;
    _cached_PatternProgress_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_PatternProgress_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "pattern", algebraicType: __AlgebraicTypeValue.String },
      { name: "startGeneration", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "masteredGeneration", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.U64) },
      { name: "bestLoss", algebraicType: __AlgebraicTypeValue.F64 },
      { name: "isMastered", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "startedAt", algebraicType: __AlgebraicTypeValue.createTimestampType() },
      { name: "masteredAt", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.createTimestampType()) },
    );
    return _cached_PatternProgress_type_value;
  },

  serialize(writer: __BinaryWriter, value: PatternProgress): void {
    __AlgebraicTypeValue.serializeValue(writer, PatternProgress.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PatternProgress {
    return __AlgebraicTypeValue.deserializeValue(reader, PatternProgress.getTypeScriptAlgebraicType());
  },

}

export default PatternProgress;


