//! Meta-Learning Manager
//!
//! Unified controller that coordinates all 6 meta-learning phases:
//! - Phase A: Enhanced Adaptive Learning (warmup, cosine annealing)
//! - Phase B: Reptile Meta-Learning (few-shot adaptation)
//! - Phase C: Population Based Training (hyperparameter evolution)
//! - Phase D: Meta-Strategy Selection (automatic approach selection)
//! - Phase E: Architecture Self-Modification (safe network changes)
//! - Phase F: Learned Optimizer (neural network-based updates)
//!
//! This manager integrates with the main training loop to provide
//! intelligent, adaptive training strategies.

use crate::nca::NCA;
use crate::learning::enhanced_meta_learning::{EnhancedAdaptiveLR, GradientStats};
use crate::learning::reptile::{ReptileMetaLearner, PatternTask, AdaptationResult};
use crate::learning::population_based_training::{
    PopulationBasedTraining, Hyperparameters, PBTStats,
};
use crate::learning::meta_strategy::{
    MetaStrategyController, TaskFeatures, LearningStrategy, StrategySelection,
};
use crate::learning::architecture_modification::{
    ArchitectureModifier, SafetyConfig, ModificationResult,
};
use crate::spacetime_client::SageDbClient;
use std::collections::VecDeque;
use std::sync::Arc;

/// Events generated by the meta-learning system
#[derive(Clone, Debug)]
pub enum MetaLearningEvent {
    /// Strategy was selected for a task
    StrategySelected { strategy: String, reason: String },
    /// Learning rate was adjusted
    LearningRateAdjusted { old_lr: f64, new_lr: f64, reason: String },
    /// Reptile performed meta-step
    ReptileMetaStep { avg_loss: f64, tasks: usize },
    /// PBT evolved population
    PBTEvolution { generation: usize, best_score: f64 },
    /// Architecture modification proposed
    ArchitectureChange { description: String, applied: bool },
    /// Curriculum advanced to new pattern
    CurriculumAdvanced { pattern: String, difficulty: f64 },
    /// Performance milestone reached
    Milestone { message: String },
}

/// Statistics from the meta-learning system
#[derive(Clone, Debug, Default)]
pub struct MetaLearningStats {
    pub current_strategy: String,
    pub current_lr: f64,
    pub warmup_complete: bool,
    pub lr_cycle_progress: f64,       // Phase A: cosine cycle progress 0-1
    pub strategy_reasoning: String,   // Why current strategy was selected
    pub reptile_meta_steps: usize,
    pub pbt_generations: usize,
    pub pbt_best_score: f64,
    pub pbt_best_lr: f64,             // Best learning rate found by PBT
    pub architecture_neurons: usize,
    pub architecture_modifications: usize,
    pub architecture_rollbacks: usize, // Phase E: rollback count
    pub total_steps: usize,
    pub avg_loss: f64,
    pub best_loss: f64,
    pub strategy_confidence: f64,
}

/// Configuration for the meta-learning manager
#[derive(Clone, Debug)]
pub struct MetaLearningConfig {
    /// Base learning rate
    pub base_lr: f64,
    /// Enable Reptile meta-learning
    pub enable_reptile: bool,
    /// Enable PBT hyperparameter evolution
    pub enable_pbt: bool,
    /// Enable architecture self-modification
    pub enable_architecture_mod: bool,
    /// PBT population size
    pub pbt_population_size: usize,
    /// How often to run PBT evolution (steps)
    pub pbt_evolution_interval: usize,
    /// How often to check architecture (steps)
    pub architecture_check_interval: usize,
}

impl Default for MetaLearningConfig {
    fn default() -> Self {
        Self {
            base_lr: 0.0001,
            enable_reptile: true,
            enable_pbt: true,
            enable_architecture_mod: true,
            pbt_population_size: 6,
            pbt_evolution_interval: 100,
            architecture_check_interval: 200,
        }
    }
}

/// Unified meta-learning manager
pub struct MetaLearningManager {
    config: MetaLearningConfig,

    // Phase A: Adaptive Learning
    adaptive_lr: EnhancedAdaptiveLR,

    // Phase B: Reptile (optional, initialized on demand)
    reptile: Option<ReptileMetaLearner>,
    reptile_initialized: bool,

    // Phase C: PBT
    pbt: Option<PopulationBasedTraining>,
    current_pbt_member: usize,

    // Phase D: Strategy Selection
    strategy_controller: MetaStrategyController,
    current_strategy: LearningStrategy,
    previous_strategy: Option<LearningStrategy>,

    // Phase E: Architecture Modification
    arch_modifier: ArchitectureModifier,

    // Tracking
    total_steps: usize,
    generation: u64,  // Current training generation for DB
    loss_history: VecDeque<f64>,
    best_loss: f64,
    events: VecDeque<MetaLearningEvent>,
    current_pattern: String,

    // Database persistence (optional)
    db_client: Option<Arc<SageDbClient>>,
}

impl MetaLearningManager {
    pub fn new(config: MetaLearningConfig) -> Self {
        let adaptive_lr = EnhancedAdaptiveLR::new(config.base_lr)
            .with_warmup(50)
            .with_cycle_length(200);

        let arch_modifier = ArchitectureModifier::new(16, SafetyConfig {
            modification_cooldown: config.architecture_check_interval,
            ..SafetyConfig::default()
        });

        Self {
            config,
            adaptive_lr,
            reptile: None,
            reptile_initialized: false,
            pbt: None,
            current_pbt_member: 0,
            strategy_controller: MetaStrategyController::new(),
            current_strategy: LearningStrategy::Standard,
            previous_strategy: None,
            arch_modifier,
            total_steps: 0,
            generation: 0,
            loss_history: VecDeque::with_capacity(100),
            best_loss: f64::MAX,
            events: VecDeque::with_capacity(50),
            current_pattern: "Circle".to_string(),
            db_client: None,
        }
    }

    /// Set the database client for persistence
    pub fn with_db_client(mut self, db_client: Arc<SageDbClient>) -> Self {
        self.db_client = Some(db_client);
        self
    }

    /// Set the database client (mutable)
    pub fn set_db_client(&mut self, db_client: Arc<SageDbClient>) {
        self.db_client = Some(db_client);
    }

    /// Update the current generation (call from training loop)
    pub fn set_generation(&mut self, gen: u64) {
        self.generation = gen;
    }

    /// Initialize with NCA (call once at start)
    pub fn initialize(&mut self, nca: &NCA) {
        // Initialize PBT if enabled
        if self.config.enable_pbt {
            self.pbt = Some(
                PopulationBasedTraining::new(self.config.pbt_population_size, nca)
                    .with_evolution_interval(self.config.pbt_evolution_interval)
            );
        }

        // Initialize Reptile if enabled
        if self.config.enable_reptile {
            self.reptile = Some(ReptileMetaLearner::new(nca));
            self.reptile_initialized = true;
        }
    }

    /// Start training on a new pattern
    pub fn start_pattern(&mut self, pattern_name: &str, loss_history: &[f64]) -> StrategySelection {
        self.current_pattern = pattern_name.to_string();

        // Extract features for this pattern
        let features = TaskFeatures::from_pattern(pattern_name, loss_history);

        // Select strategy
        let selection = self.strategy_controller.start_task(features);

        // Check if strategy changed
        let strategy_changed = self.previous_strategy != Some(selection.strategy);
        self.previous_strategy = Some(self.current_strategy);
        self.current_strategy = selection.strategy;

        // Log event
        self.add_event(MetaLearningEvent::StrategySelected {
            strategy: selection.strategy.name().to_string(),
            reason: selection.reasoning.clone(),
        });

        // Persist strategy change to DB
        if strategy_changed {
            if let Some(db) = &self.db_client {
                let _ = db.record_strategy_change(
                    self.generation,
                    selection.strategy.name(),
                    &selection.reasoning,
                    self.best_loss,
                );
            }
        }

        // Reset adaptive LR for new pattern
        let difficulty = match pattern_name.to_lowercase().as_str() {
            "circle" => 0.2,
            "square" => 0.8,
            "cross" => 0.5,
            "spiral" => 0.7,
            _ => 0.5,
        };
        self.adaptive_lr.reset_for_pattern(difficulty);

        selection
    }

    /// Get learning rate for current step
    pub fn get_learning_rate(&mut self, loss: f64, gradient_magnitude: f64) -> f64 {
        self.total_steps += 1;

        // Track loss
        self.loss_history.push_back(loss);
        if self.loss_history.len() > 100 {
            self.loss_history.pop_front();
        }
        self.best_loss = self.best_loss.min(loss);

        // Update adaptive LR
        let grad_stats = GradientStats::new(gradient_magnitude, 0.01);
        self.adaptive_lr.step(loss, Some(grad_stats));
        let base_lr = self.adaptive_lr.get_rate();

        // Apply strategy-specific multiplier
        let lr = match self.current_strategy {
            LearningStrategy::Standard => base_lr,
            LearningStrategy::Reptile => base_lr * 0.8,  // Slightly lower for stability
            LearningStrategy::PBT => {
                // Use PBT hyperparameters if available
                if let Some(pbt) = &self.pbt {
                    if let Some(hp) = pbt.get_hyperparams(self.current_pbt_member) {
                        hp.learning_rate
                    } else {
                        base_lr
                    }
                } else {
                    base_lr
                }
            }
            LearningStrategy::SelfPaced => base_lr * 0.9,
            LearningStrategy::Ensemble => base_lr,
        };

        // Update architecture modifier
        if self.config.enable_architecture_mod {
            self.arch_modifier.update(loss, gradient_magnitude, None);
        }

        lr
    }

    /// Record training result (call after each training step)
    pub fn record_result(&mut self, loss: f64, nca: &NCA) {
        // Record for PBT
        if self.config.enable_pbt {
            if let Some(pbt) = &mut self.pbt {
                pbt.record_evaluation(self.current_pbt_member, loss, nca);

                // Rotate through population
                self.current_pbt_member = (self.current_pbt_member + 1) % self.config.pbt_population_size;

                // Check for evolution
                let stats = pbt.get_stats();
                if stats.evolutions > 0 && self.total_steps % self.config.pbt_evolution_interval == 0 {
                    self.add_event(MetaLearningEvent::PBTEvolution {
                        generation: stats.evolutions,
                        best_score: stats.best_score,
                    });

                    // Persist best hyperparameters to DB
                    if let Some(db) = &self.db_client {
                        let _ = db.record_hyperparameters(
                            self.generation,
                            stats.best_lr,
                            8,  // batch_size - could get from PBT
                            100, // evolution_steps - could get from PBT
                            0.1, // mutation_rate - could get from PBT
                            stats.best_score,
                            None,
                            true, // is_elite
                        );
                    }
                }
            }
        }

        // Check architecture modification periodically
        if self.config.enable_architecture_mod &&
           self.total_steps % self.config.architecture_check_interval == 0 {
            self.check_architecture_modification();
        }

        // Check for milestones
        if loss < 0.1 && self.best_loss >= 0.1 {
            self.add_event(MetaLearningEvent::Milestone {
                message: format!("Loss dropped below 0.1 on {}", self.current_pattern),
            });
        }
    }

    /// Perform Reptile meta-step (call periodically, e.g., every 500 steps)
    pub fn reptile_meta_step(&mut self, nca: &mut NCA, tasks: &[PatternTask]) {
        if !self.config.enable_reptile {
            return;
        }

        if let Some(reptile) = &mut self.reptile {
            let result = reptile.meta_step(nca, tasks);
            self.add_event(MetaLearningEvent::ReptileMetaStep {
                avg_loss: result.avg_final_loss,
                tasks: result.tasks_sampled,
            });
        }
    }

    /// Adapt to a new pattern using Reptile (few-shot)
    pub fn reptile_adapt(&mut self, nca: &mut NCA, task: &PatternTask, max_steps: usize) -> Option<AdaptationResult> {
        if !self.config.enable_reptile {
            return None;
        }

        if let Some(reptile) = &mut self.reptile {
            let start = std::time::Instant::now();
            let result = reptile.adapt(nca, task, max_steps);
            let elapsed_ms = start.elapsed().as_millis() as u64;

            // Persist adaptation result to DB
            if let Some(db) = &self.db_client {
                let _ = db.record_few_shot_adaptation(
                    self.generation,
                    &task.name,
                    1, // shots_used (single task)
                    result.steps_taken as u32,
                    result.initial_loss,
                    result.final_loss,
                    "meta_weights", // transfer source
                    elapsed_ms,
                );
            }

            Some(result)
        } else {
            None
        }
    }

    /// Check and potentially apply architecture modification
    fn check_architecture_modification(&mut self) {
        let result = self.arch_modifier.try_modification();
        let hidden_neurons = self.arch_modifier.state().hidden_neurons;

        match result {
            ModificationResult::Applied { modification, reason, .. } => {
                // Calculate sizes before mutable borrow
                let (change_type, old_size, new_size) = match &modification {
                    crate::learning::architecture_modification::ModificationType::AddNeurons { count, .. } => {
                        ("add_neurons", hidden_neurons as u32 - *count as u32, hidden_neurons as u32)
                    }
                    crate::learning::architecture_modification::ModificationType::RemoveNeurons { count, .. } => {
                        ("remove_neurons", hidden_neurons as u32 + *count as u32, hidden_neurons as u32)
                    }
                    crate::learning::architecture_modification::ModificationType::ScaleActivation { .. } => {
                        ("scale_activation", hidden_neurons as u32, hidden_neurons as u32)
                    }
                    crate::learning::architecture_modification::ModificationType::AdjustDropout { .. } => {
                        ("adjust_dropout", hidden_neurons as u32, hidden_neurons as u32)
                    }
                    crate::learning::architecture_modification::ModificationType::None => {
                        ("none", hidden_neurons as u32, hidden_neurons as u32)
                    }
                };
                let description = format!("{}: {}", modification.description(), reason);

                self.add_event(MetaLearningEvent::ArchitectureChange {
                    description,
                    applied: true,
                });

                // Persist architecture change to DB
                if let Some(db) = &self.db_client {
                    let _ = db.record_architecture_change(
                        self.generation,
                        change_type,
                        "hidden_layer",
                        old_size,
                        new_size,
                        &reason,
                        self.best_loss,
                    );
                }
            }
            ModificationResult::NeedsApproval { modification, reason } => {
                self.add_event(MetaLearningEvent::ArchitectureChange {
                    description: format!("NEEDS APPROVAL: {} - {}", modification.description(), reason),
                    applied: false,
                });
            }
            _ => {}
        }
    }

    /// Get current hyperparameters (from PBT or defaults)
    pub fn get_hyperparameters(&self) -> Hyperparameters {
        if let Some(pbt) = &self.pbt {
            pbt.get_hyperparams(self.current_pbt_member)
                .cloned()
                .unwrap_or_default()
        } else {
            Hyperparameters::default()
        }
    }

    /// Get current statistics
    pub fn get_stats(&self) -> MetaLearningStats {
        let avg_loss = if self.loss_history.is_empty() {
            1.0
        } else {
            self.loss_history.iter().sum::<f64>() / self.loss_history.len() as f64
        };

        let diag = self.adaptive_lr.get_diagnostics();

        let (pbt_generations, pbt_best_score, pbt_best_lr) = if let Some(pbt) = &self.pbt {
            let stats = pbt.get_stats();
            (stats.evolutions, stats.best_score, stats.best_lr)
        } else {
            (0, 0.0, self.config.base_lr)
        };

        let arch_stats = self.arch_modifier.stats();

        // Calculate LR cycle progress (for cosine annealing visualization)
        let lr_cycle_progress = if diag.warmup_complete {
            // After warmup, show cosine cycle progress based on total steps
            let cycle_length = 1000.0; // One full cosine cycle
            (self.total_steps as f64 % cycle_length) / cycle_length
        } else {
            // During warmup, show warmup progress
            diag.warmup_progress
        };

        MetaLearningStats {
            current_strategy: self.current_strategy.name().to_string(),
            current_lr: diag.current_rate,
            warmup_complete: diag.warmup_complete,
            lr_cycle_progress,
            strategy_reasoning: self.current_strategy.reason().to_string(),
            reptile_meta_steps: if self.reptile.is_some() { self.total_steps / 500 } else { 0 },
            pbt_generations,
            pbt_best_score,
            pbt_best_lr,
            architecture_neurons: self.arch_modifier.state().hidden_neurons,
            architecture_modifications: arch_stats.applied,
            architecture_rollbacks: arch_stats.rolled_back,
            total_steps: self.total_steps,
            avg_loss,
            best_loss: self.best_loss,
            strategy_confidence: self.current_strategy.confidence(),
        }
    }

    /// Get recent events
    pub fn get_events(&self) -> Vec<MetaLearningEvent> {
        self.events.iter().cloned().collect()
    }

    /// Get and clear events (for displaying in UI)
    pub fn drain_events(&mut self) -> Vec<MetaLearningEvent> {
        self.events.drain(..).collect()
    }

    /// Add an event
    fn add_event(&mut self, event: MetaLearningEvent) {
        self.events.push_back(event);
        if self.events.len() > 50 {
            self.events.pop_front();
        }
    }

    /// Get current strategy
    pub fn current_strategy(&self) -> LearningStrategy {
        self.current_strategy
    }

    /// Check if Reptile is enabled and initialized
    pub fn reptile_available(&self) -> bool {
        self.config.enable_reptile && self.reptile_initialized
    }

    /// Get PBT stats if available
    pub fn pbt_stats(&self) -> Option<PBTStats> {
        self.pbt.as_ref().map(|p| p.get_stats())
    }

    /// Save optimizer snapshot to DB (call periodically or at milestones)
    pub fn save_optimizer_snapshot(&self, optimizer_weights_json: &str) {
        if let Some(db) = &self.db_client {
            let stats = self.get_stats();
            let _ = db.save_optimizer_snapshot(
                self.generation,
                &stats.current_strategy,
                optimizer_weights_json,
                stats.current_lr,
                if stats.best_loss < 0.1 { 1.0 } else { stats.total_steps as f64 / 1000.0 },
                if stats.avg_loss.is_finite() { 1.0 - stats.avg_loss.min(1.0) } else { 0.5 },
            );
        }
    }
}
